# This file is used to run integration tests on travis
version: '3'
services:

  gostresser:
    network_mode: bridge
    image: daocloud.io/zhwei820/gostresser
    ports:
    - 8082:80
    - 8179:8179
    environment:
      APP_GOSTRESSER_URI: http://localhost:8179
      BUILD_ENV: not_dev
    links:
    - mongodb
    volumes:
    - ./config:/code/config
    command: sh ./start.sh

  mongodb:
    network_mode: bridge
    image: mongo:3.2
    container_name: mongodb
    restart: always
    volumes:
      - ./data/mongo:/data/db

