// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: say.proto

package say

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SayInput struct {
	Query         string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber    int64  `protobuf:"zigzag64,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage int64  `protobuf:"zigzag64,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
}

func (m *SayInput) Reset()         { *m = SayInput{} }
func (m *SayInput) String() string { return proto.CompactTextString(m) }
func (*SayInput) ProtoMessage()    {}
func (*SayInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_say_8c256bcd87794453, []int{0}
}
func (m *SayInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SayInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SayInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SayInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayInput.Merge(dst, src)
}
func (m *SayInput) XXX_Size() int {
	return m.Size()
}
func (m *SayInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SayInput.DiscardUnknown(m)
}

var xxx_messageInfo_SayInput proto.InternalMessageInfo

func (m *SayInput) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SayInput) GetPageNumber() int64 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SayInput) GetResultPerPage() int64 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

type SayOutput struct {
	Url      string       `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title    string       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets []string     `protobuf:"bytes,3,rep,name=snippets" json:"snippets,omitempty"`
	Results  []*SayResult `protobuf:"bytes,4,rep,name=results" json:"results,omitempty"`
}

func (m *SayOutput) Reset()         { *m = SayOutput{} }
func (m *SayOutput) String() string { return proto.CompactTextString(m) }
func (*SayOutput) ProtoMessage()    {}
func (*SayOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_say_8c256bcd87794453, []int{1}
}
func (m *SayOutput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SayOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SayOutput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SayOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayOutput.Merge(dst, src)
}
func (m *SayOutput) XXX_Size() int {
	return m.Size()
}
func (m *SayOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SayOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SayOutput proto.InternalMessageInfo

func (m *SayOutput) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SayOutput) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SayOutput) GetSnippets() []string {
	if m != nil {
		return m.Snippets
	}
	return nil
}

func (m *SayOutput) GetResults() []*SayResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type SayResult struct {
	Url      string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title    string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets []string `protobuf:"bytes,3,rep,name=snippets" json:"snippets,omitempty"`
}

func (m *SayResult) Reset()         { *m = SayResult{} }
func (m *SayResult) String() string { return proto.CompactTextString(m) }
func (*SayResult) ProtoMessage()    {}
func (*SayResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_say_8c256bcd87794453, []int{2}
}
func (m *SayResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SayResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SayResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SayResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResult.Merge(dst, src)
}
func (m *SayResult) XXX_Size() int {
	return m.Size()
}
func (m *SayResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResult.DiscardUnknown(m)
}

var xxx_messageInfo_SayResult proto.InternalMessageInfo

func (m *SayResult) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SayResult) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SayResult) GetSnippets() []string {
	if m != nil {
		return m.Snippets
	}
	return nil
}

func init() {
	proto.RegisterType((*SayInput)(nil), "say.SayInput")
	proto.RegisterType((*SayOutput)(nil), "say.SayOutput")
	proto.RegisterType((*SayResult)(nil), "say.SayResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SayServiceClient is the client API for SayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SayServiceClient interface {
	SayHello(ctx context.Context, in *SayInput, opts ...grpc.CallOption) (*SayOutput, error)
}

type sayServiceClient struct {
	cc *grpc.ClientConn
}

func NewSayServiceClient(cc *grpc.ClientConn) SayServiceClient {
	return &sayServiceClient{cc}
}

func (c *sayServiceClient) SayHello(ctx context.Context, in *SayInput, opts ...grpc.CallOption) (*SayOutput, error) {
	out := new(SayOutput)
	err := c.cc.Invoke(ctx, "/say.SayService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayServiceServer is the server API for SayService service.
type SayServiceServer interface {
	SayHello(context.Context, *SayInput) (*SayOutput, error)
}

func RegisterSayServiceServer(s *grpc.Server, srv SayServiceServer) {
	s.RegisterService(&_SayService_serviceDesc, srv)
}

func _SayService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/say.SayService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayServiceServer).SayHello(ctx, req.(*SayInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _SayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "say.SayService",
	HandlerType: (*SayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SayService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "say.proto",
}

func (m *SayInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SayInput) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Query) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSay(dAtA, i, uint64(len(m.Query)))
		i += copy(dAtA[i:], m.Query)
	}
	if m.PageNumber != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSay(dAtA, i, uint64((uint64(m.PageNumber)<<1)^uint64((m.PageNumber>>63))))
	}
	if m.ResultPerPage != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintSay(dAtA, i, uint64((uint64(m.ResultPerPage)<<1)^uint64((m.ResultPerPage>>63))))
	}
	return i, nil
}

func (m *SayOutput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SayOutput) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Url) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSay(dAtA, i, uint64(len(m.Url)))
		i += copy(dAtA[i:], m.Url)
	}
	if len(m.Title) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSay(dAtA, i, uint64(len(m.Title)))
		i += copy(dAtA[i:], m.Title)
	}
	if len(m.Snippets) > 0 {
		for _, s := range m.Snippets {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Results) > 0 {
		for _, msg := range m.Results {
			dAtA[i] = 0x22
			i++
			i = encodeVarintSay(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *SayResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SayResult) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Url) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSay(dAtA, i, uint64(len(m.Url)))
		i += copy(dAtA[i:], m.Url)
	}
	if len(m.Title) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSay(dAtA, i, uint64(len(m.Title)))
		i += copy(dAtA[i:], m.Title)
	}
	if len(m.Snippets) > 0 {
		for _, s := range m.Snippets {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func encodeVarintSay(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *SayInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Query)
	if l > 0 {
		n += 1 + l + sovSay(uint64(l))
	}
	if m.PageNumber != 0 {
		n += 1 + sozSay(uint64(m.PageNumber))
	}
	if m.ResultPerPage != 0 {
		n += 1 + sozSay(uint64(m.ResultPerPage))
	}
	return n
}

func (m *SayOutput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovSay(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovSay(uint64(l))
	}
	if len(m.Snippets) > 0 {
		for _, s := range m.Snippets {
			l = len(s)
			n += 1 + l + sovSay(uint64(l))
		}
	}
	if len(m.Results) > 0 {
		for _, e := range m.Results {
			l = e.Size()
			n += 1 + l + sovSay(uint64(l))
		}
	}
	return n
}

func (m *SayResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovSay(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovSay(uint64(l))
	}
	if len(m.Snippets) > 0 {
		for _, s := range m.Snippets {
			l = len(s)
			n += 1 + l + sovSay(uint64(l))
		}
	}
	return n
}

func sovSay(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSay(x uint64) (n int) {
	return sovSay(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SayInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SayInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SayInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSay
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Query = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageNumber", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.PageNumber = int64(v)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultPerPage", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.ResultPerPage = int64(v)
		default:
			iNdEx = preIndex
			skippy, err := skipSay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SayOutput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SayOutput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SayOutput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSay
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSay
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snippets", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSay
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Snippets = append(m.Snippets, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Results", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSay
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Results = append(m.Results, &SayResult{})
			if err := m.Results[len(m.Results)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SayResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SayResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SayResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSay
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSay
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snippets", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSay
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Snippets = append(m.Snippets, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSay(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSay
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSay
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSay
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSay(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSay = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSay   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("say.proto", fileDescriptor_say_8c256bcd87794453) }

var fileDescriptor_say_8c256bcd87794453 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xcb, 0x4a, 0x03, 0x31,
	0x14, 0x86, 0x27, 0xc6, 0x4b, 0xe7, 0x94, 0xaa, 0x04, 0x17, 0x43, 0x17, 0x71, 0x98, 0x85, 0x0c,
	0x08, 0x5d, 0xd4, 0x95, 0x5b, 0x57, 0x75, 0x63, 0x4b, 0xe6, 0x01, 0x4a, 0x2a, 0x87, 0x32, 0x30,
	0xb6, 0x31, 0x17, 0x21, 0x6f, 0xe1, 0x63, 0xb9, 0xec, 0xd2, 0xa5, 0x74, 0x5e, 0x44, 0x92, 0xd8,
	0x3e, 0x81, 0xbb, 0xfc, 0xdf, 0x09, 0x7c, 0xe7, 0x02, 0xb9, 0x91, 0x7e, 0xa2, 0xf4, 0xd6, 0x6e,
	0x19, 0x35, 0xd2, 0x57, 0x2d, 0x0c, 0x1a, 0xe9, 0x9f, 0x37, 0xca, 0x59, 0x76, 0x03, 0x67, 0xef,
	0x0e, 0xb5, 0x2f, 0x48, 0x49, 0xea, 0x5c, 0xa4, 0xc0, 0x6e, 0x61, 0xa8, 0xe4, 0x1a, 0x97, 0x1b,
	0xf7, 0xb6, 0x42, 0x5d, 0x9c, 0x94, 0xa4, 0x66, 0x02, 0x02, 0x7a, 0x89, 0x84, 0xdd, 0xc1, 0x95,
	0x46, 0xe3, 0x3a, 0xbb, 0x54, 0xa8, 0x97, 0xa1, 0x50, 0xd0, 0xf8, 0x69, 0x94, 0xf0, 0x02, 0xf5,
	0x42, 0xae, 0xb1, 0xf2, 0x90, 0x37, 0xd2, 0xcf, 0x9d, 0x0d, 0xae, 0x6b, 0xa0, 0x4e, 0x77, 0x7f,
	0xa6, 0xf0, 0x0c, 0x76, 0xdb, 0xda, 0x0e, 0xa3, 0x21, 0x17, 0x29, 0xb0, 0x31, 0x0c, 0xcc, 0xa6,
	0x55, 0x0a, 0xad, 0x29, 0x68, 0x49, 0xeb, 0x5c, 0x1c, 0x33, 0xab, 0xe1, 0x22, 0x19, 0x4c, 0x71,
	0x5a, 0xd2, 0x7a, 0x38, 0xbd, 0x9c, 0x84, 0xe9, 0x1a, 0xe9, 0x45, 0xc4, 0xe2, 0x50, 0xae, 0xe6,
	0x51, 0x9d, 0xe8, 0x7f, 0xa8, 0xa7, 0x8f, 0x00, 0x8d, 0xf4, 0x0d, 0xea, 0x8f, 0xf6, 0x15, 0xd9,
	0x7d, 0x5c, 0xe2, 0x0c, 0xbb, 0x6e, 0xcb, 0x46, 0x87, 0x1e, 0xe2, 0x4e, 0xc7, 0xc7, 0x96, 0xd2,
	0xdc, 0x55, 0xf6, 0x34, 0xfe, 0xda, 0x73, 0xb2, 0xdb, 0x73, 0xf2, 0xb3, 0xe7, 0xe4, 0xb3, 0xe7,
	0xd9, 0xae, 0xe7, 0xd9, 0x77, 0xcf, 0xb3, 0x19, 0x59, 0x9d, 0xc7, 0xcb, 0x3c, 0xfc, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xa6, 0x3d, 0x93, 0x69, 0xa6, 0x01, 0x00, 0x00,
}
