# This file is used to run integration tests on travis
version: '3'
services:

  GoStresser:
      image: daocloud.io/zhwei820/GoStresser
      ports:
        - "8082:80"
      environment:
        REACT_APP_GOSTRESSER_URI: http://localhost:8081
